'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    '類別透過 ResGen 或 Visual Studio 這類工具。
    '若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    '(利用 /str 選項)，或重建您的 VS 專案。
    '''<summary>
    '''  用於查詢當地語系化字串等的強類型資源類別。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  傳回這個類別使用的快取的 ResourceManager 執行個體。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApp3.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        '''  使用這個強類型資源類別的資源查閱。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property _____BOSS2______burned_去背() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_____BOSS2______burned_去背", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property ___BOSS_2______burned_去背() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("___BOSS_2______burned_去背", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property _01__ホシノキズナ() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_01__ホシノキズナ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property _02__Decision() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_02__Decision", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property _123() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("_123", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property _250px_13_02_misheru() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_250px_13_02_misheru", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property _8gr8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_8gr8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property BOSS1遊戲用() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BOSS1遊戲用", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property BOSS2遊戲用() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BOSS2遊戲用", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property Live2D_13_u_01_00_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Live2D_13_u_01_00_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property Ring() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ring", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 剩餘生命值() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("剩餘生命值", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 困難度() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("困難度", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 外空() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("外空", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 姆咪2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("姆咪2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 姆咪姆咪() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("姆咪姆咪", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 姆咪姆咪1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("姆咪姆咪1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 姆咪機() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("姆咪機", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 姆咪紀錄() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("姆咪紀錄", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 子彈() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("子彈", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 小BOSS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("小BOSS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 小兵() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("小兵", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 日期() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("日期", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 更改背景音樂() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("更改背景音樂", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 櫻花樹下() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("櫻花樹下", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 玩家名稱() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("玩家名稱", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 美紀BOSS1劇情用() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("美紀BOSS1劇情用", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 超級姆咪() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("超級姆咪", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 輸入遊戲暱稱() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("輸入遊戲暱稱", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 遊戲分數() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("遊戲分數", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 難度2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("難度2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
